### ISSUE TITLE
Unable to deploy the charm with the command mentione. 

### ISSUE THREAD

**Issue by raghav20** [juju-solutions/layer-apache-bigtop-spark#2]

**Comment by raghav20** [comment]
HI all, 
I was looking for a spark charm for  production deployment. It should support either version 1.6 and 2.

**Comment by ktsakalozos** [comment]
Hi @raghav20, this repository is not used anymore. The code of the charms using bigtop binaries is pushed upstream to https://github.com/apache/bigtop . In particular the spark charm is here: https://github.com/apache/bigtop/tree/master/bigtop-packages/src/charm/spark/layer-spark

You mention you need a spark charm for 1.6 and 2.0. The apache bigtop project is actually about to have a new release that would include binaries for the two spark versions in question. It is in our intention to stay aligned with bigtop therefore our charms will receive proper updates.

Would you care to share some more details on your use case? What kind of production deployment are we talking about? Knowing your needs would allow us to properly prioritise our work. We appreciate your feedback.

**Comment by kwmonroe** [comment]
Hi @raghav20, I'm going to close this PR out.  This repo was created early in our Apache Bigtop charming effort and is not really monitored anymore (i'll look into disabling it altogether soon).  Now we have a development fork of the bigtop tree that houses all of our bigtop charms.  Issues with the bigtop spark charm should be raised there instead:

https://github.com/juju-solutions/bigtop/issues

As @ktsakalozos mentioned, bigtop has a new release coming soon that will at least include spark-2.  If you still have questions/concerns with a spark charm suitable for production deployment, please consider opening an issue at the above link.  Thanks!
